/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as QueryRouteImport } from './routes/query'

const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const QueryRoute = QueryRouteImport.update({
  id: '/query',
  path: '/query',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/trips': typeof TripsRoute
  '/payments': typeof PaymentsRoute
  '/safety': typeof SafetyRoute
  '/query': typeof QueryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/trips': typeof TripsRoute
  '/payments': typeof PaymentsRoute
  '/safety': typeof SafetyRoute
  '/query': typeof QueryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/trips': typeof TripsRoute
  '/payments': typeof PaymentsRoute
  '/safety': typeof SafetyRoute
  '/query': typeof QueryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/matches'
    | '/onboarding'
    | '/pricing'
    | '/profile'
    | '/search'
    | '/trips'
    | '/payments'
    | '/safety'
    | '/query'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/matches'
    | '/onboarding'
    | '/pricing'
    | '/profile'
    | '/search'
    | '/trips'
    | '/payments'
    | '/safety'
    | '/query'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/matches'
    | '/onboarding'
    | '/pricing'
    | '/profile'
    | '/search'
    | '/trips'
    | '/payments'
    | '/safety'
    | '/query'
  fileRoutesById: FileRoutesById
}

declare module '@tanstack/react-router' {
  interface FileRoutesByFullPath {
    '/': typeof IndexRoute
    '/login': typeof LoginRoute
    '/matches': typeof MatchesRoute
    '/onboarding': typeof OnboardingRoute
    '/pricing': typeof PricingRoute
    '/profile': typeof ProfileRoute
    '/search': typeof SearchRoute
    '/trips': typeof TripsRoute
    '/payments': typeof PaymentsRoute
    '/safety': typeof SafetyRoute
    '/query': typeof QueryRoute
  }
  interface FileRoutesByTo {
    '/': typeof IndexRoute
    '/login': typeof LoginRoute
    '/matches': typeof MatchesRoute
    '/onboarding': typeof OnboardingRoute
    '/pricing': typeof PricingRoute
    '/profile': typeof ProfileRoute
    '/search': typeof SearchRoute
    '/trips': typeof TripsRoute
    '/payments': typeof PaymentsRoute
    '/safety': typeof SafetyRoute
    '/query': typeof QueryRoute
  }
  interface FileRoutesById {
    __root__: typeof rootRouteImport
    '/': typeof IndexRoute
    '/login': typeof LoginRoute
    '/matches': typeof MatchesRoute
    '/onboarding': typeof OnboardingRoute
    '/pricing': typeof PricingRoute
    '/profile': typeof ProfileRoute
    '/search': typeof SearchRoute
    '/trips': typeof TripsRoute
    '/payments': typeof PaymentsRoute
    '/safety': typeof SafetyRoute
    '/query': typeof QueryRoute
  }
}

export interface RootRouteChildren {
  index: typeof IndexRoute
  login: typeof LoginRoute
  matches: typeof MatchesRoute
  onboarding: typeof OnboardingRoute
  pricing: typeof PricingRoute
  profile: typeof ProfileRoute
  search: typeof SearchRoute
  trips: typeof TripsRoute
  payments: typeof PaymentsRoute
  safety: typeof SafetyRoute
  query: typeof QueryRoute
}

const rootRouteChildren: RootRouteChildren = {
  index: IndexRoute,
  login: LoginRoute,
  matches: MatchesRoute,
  onboarding: OnboardingRoute,
  pricing: PricingRoute,
  profile: ProfileRoute,
  search: SearchRoute,
  trips: TripsRoute,
  payments: PaymentsRoute,
  safety: SafetyRoute,
  query: QueryRoute,
}

export { rootRouteChildren }

export const routeTree = rootRouteImport.update({
  id: '__root__',
  path: '/',
  getParentRoute: () => undefined,
  children: [
    IndexRoute,
    LoginRoute,
    MatchesRoute,
    OnboardingRoute,
    PricingRoute,
    ProfileRoute,
    SearchRoute,
    TripsRoute,
    PaymentsRoute,
    SafetyRoute,
    QueryRoute,
  ],
} as any)
